name: CI/CD to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t stenny17/dummy-eks-app:$IMAGE_TAG .
          docker push stenny17/dummy-eks-app:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --region us-west-2 --name my-eks-cluster

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/dummy-app dummy-app=stenny17/dummy-eks-app:${{ env.IMAGE_TAG }} -n dummy
          kubectl apply -f k8s/

