name: CI/CD to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Log in to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 2: Build & Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t stenny17/dummy-eks-app:latest .
          docker push stenny17/dummy-eks-app:latest

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Step 4: Update kubeconfig for EKS
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name my-eks-cluster --region us-west-2

      # Step 5: Deploy to EKS
      - name: Deploy to EKS
        run: |
          kubectl set image deployment/dummy-app dummy-app=stenny17/dummy-eks-app:latest -n dummy
          kubectl rollout status deployment/dummy-app -n dummy

